# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uygWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 634)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/nokta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("* {\n"
"font-size:15px;\n"
"font-family:Century Gothic, sans-serif;\n"
"}\n"
"#MainWindow{\n"
"    background-image: url(:images/bg.png);\n"
"\n"
"} \n"
"QWidget{\n"
"    background-image: url(:images/bg.png);\n"
"}\n"
"\n"
"QFrame{\n"
"    background-image: url(:images/bg.png);\n"
"    border:solid 5px green;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background:red;\n"
"    color:white;\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background:red;\n"
"border-style:inset;\n"
"border-radius:10px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:green;\n"
"color:white;\n"
"border-style:inset;\n"
"border-radius:10px\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"/*background:#2c1139;*/\n"
"background:#1d3239;\n"
"color:white;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    background:rgba(85,170,255,0);\n"
"    color:white;\n"
"}\n"
"\n"
"#label_giren_sayisi{\n"
"    padding-left:5px;\n"
"}\n"
"#labelUyari{\n"
"    font-size:12px;\n"
"    font-style:italic;\n"
"    color:white;\n"
"    background:rgba(85,170,255,0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 661, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_video = QtWidgets.QLabel(self.frame)
        self.label_video.setGeometry(QtCore.QRect(10, 10, 641, 511))
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(710, 30, 311, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_giren_sayisi = QtWidgets.QLabel(self.frame_2)
        self.label_giren_sayisi.setGeometry(QtCore.QRect(10, 10, 291, 51))
        self.label_giren_sayisi.setText("")
        self.label_giren_sayisi.setObjectName("label_giren_sayisi")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(710, 120, 311, 211))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutSaat = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutSaat.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutSaat.setObjectName("verticalLayoutSaat")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(710, 350, 311, 211))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 291, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayoutGun = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayoutGun.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutGun.setObjectName("verticalLayoutGun")
        self.radioButtonDemo = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonDemo.setGeometry(QtCore.QRect(790, 0, 71, 25))
        self.radioButtonDemo.setObjectName("radioButtonDemo")
        self.radioButtonCanli = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonCanli.setGeometry(QtCore.QRect(720, 0, 61, 25))
        self.radioButtonCanli.setChecked(True)
        self.radioButtonCanli.setObjectName("radioButtonCanli")
        self.pushButtonBaslat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBaslat.setGeometry(QtCore.QRect(860, 0, 151, 27))
        self.pushButtonBaslat.setObjectName("pushButtonBaslat")
        self.labelUyari = QtWidgets.QLabel(self.centralwidget)
        self.labelUyari.setGeometry(QtCore.QRect(40, 570, 641, 19))
        self.labelUyari.setObjectName("labelUyari")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1051, 23))
        self.menubar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.menubar.setObjectName("menubar")
        self.menuAnasayfa = QtWidgets.QMenu(self.menubar)
        self.menuAnasayfa.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.menuAnasayfa.setObjectName("menuAnasayfa")
        self.menuAyarlar = QtWidgets.QMenu(self.menubar)
        self.menuAyarlar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.menuAyarlar.setObjectName("menuAyarlar")
        self.menuKullanicilar = QtWidgets.QMenu(self.menubar)
        self.menuKullanicilar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.menuKullanicilar.setObjectName("menuKullanicilar")
        self.menuLoglar = QtWidgets.QMenu(self.menubar)
        self.menuLoglar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.menuLoglar.setObjectName("menuLoglar")
        self.menuHakkinda = QtWidgets.QMenu(self.menubar)
        self.menuHakkinda.setObjectName("menuHakkinda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAyarlar = QtWidgets.QAction(MainWindow)
        self.actionAyarlar.setObjectName("actionAyarlar")
        self.actionAyar = QtWidgets.QAction(MainWindow)
        self.actionAyar.setObjectName("actionAyar")
        self.actionAyarlar_2 = QtWidgets.QAction(MainWindow)
        self.actionAyarlar_2.setObjectName("actionAyarlar_2")
        self.actionKulan_c_lar = QtWidgets.QAction(MainWindow)
        self.actionKulan_c_lar.setObjectName("actionKulan_c_lar")
        self.actionKapat = QtWidgets.QAction(MainWindow)
        self.actionKapat.setObjectName("actionKapat")
        self.actionKullanicilar = QtWidgets.QAction(MainWindow)
        self.actionKullanicilar.setObjectName("actionKullanicilar")
        self.actionLogKayitlar = QtWidgets.QAction(MainWindow)
        self.actionLogKayitlar.setObjectName("actionLogKayitlar")
        self.actionHakkinda = QtWidgets.QAction(MainWindow)
        self.actionHakkinda.setObjectName("actionHakkinda")
        self.menuAnasayfa.addAction(self.actionKapat)
        self.menuAyarlar.addAction(self.actionAyar)
        self.menuKullanicilar.addAction(self.actionKullanicilar)
        self.menuLoglar.addAction(self.actionLogKayitlar)
        self.menuHakkinda.addAction(self.actionHakkinda)
        self.menubar.addAction(self.menuAnasayfa.menuAction())
        self.menubar.addAction(self.menuAyarlar.menuAction())
        self.menubar.addAction(self.menuKullanicilar.menuAction())
        self.menubar.addAction(self.menuLoglar.menuAction())
        self.menubar.addAction(self.menuHakkinda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kaç Kişi Var"))
        self.radioButtonDemo.setText(_translate("MainWindow", "Demo"))
        self.radioButtonCanli.setText(_translate("MainWindow", "Canlı"))
        self.pushButtonBaslat.setText(_translate("MainWindow", "Sayımı Başlat"))
        self.labelUyari.setText(_translate("MainWindow", "* Canlı modda görüntü alamıyorsanız Ayarlar ekranından USB ID bilgisini güncelleyiniz!"))
        self.menuAnasayfa.setTitle(_translate("MainWindow", "Dosya"))
        self.menuAyarlar.setTitle(_translate("MainWindow", "Ayarlar"))
        self.menuKullanicilar.setTitle(_translate("MainWindow", "Kullanıcılar"))
        self.menuLoglar.setTitle(_translate("MainWindow", "Loglar"))
        self.menuHakkinda.setTitle(_translate("MainWindow", "Hakkında"))
        self.actionAyarlar.setText(_translate("MainWindow", "Ayarlar"))
        self.actionAyarlar.setToolTip(_translate("MainWindow", "ayar"))
        self.actionAyarlar.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionAyar.setText(_translate("MainWindow", "Ayarlar"))
        self.actionAyarlar_2.setText(_translate("MainWindow", "Ayarlar"))
        self.actionKulan_c_lar.setText(_translate("MainWindow", "Kulanıcılar"))
        self.actionKapat.setText(_translate("MainWindow", "Çıkış"))
        self.actionKullanicilar.setText(_translate("MainWindow", "Kullanıcılar"))
        self.actionLogKayitlar.setText(_translate("MainWindow", "Log Kayıtları"))
        self.actionHakkinda.setText(_translate("MainWindow", "Hakkında"))
import views.sources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
