# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayarlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AyarlarForm(object):
    def setupUi(self, AyarlarForm):
        AyarlarForm.setObjectName("AyarlarForm")
        AyarlarForm.resize(878, 358)
        AyarlarForm.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/bg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AyarlarForm.setWindowIcon(icon)
        AyarlarForm.setStyleSheet("* {\n"
"font-size:15px;\n"
"font-family:Century Gothic, sans-serif;\n"
"}\n"
"QWidget{\n"
"    background-image: url(:/images/bg.png);\n"
"    background:#28595e\n"
"}\n"
"QLineEdit, QComboBox, QTimeEdit{\n"
"color:#333533;\n"
"background:rgba(85,170,255,100);\n"
"font-size:18px;\n"
"border-style:outset;\n"
"border: solid 1px;\n"
"border-radius:10px\n"
"}\n"
"QPushButton{\n"
"background-color:#4361ee;\n"
"border-style:outset;\n"
"border-radius:10px\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#ef233c;\n"
"border-style:inset;\n"
"border-radius:10px\n"
"}\n"
"QCheckBox{\n"
"background:rgba(85,170,255,0);\n"
"border-style:outset;\n"
"color:white;\n"
"}\n"
"QLabel{\n"
"background:rgba(85,170,255,0);\n"
"color:white;\n"
"font-style:italic bold;\n"
"font-size:14px;\n"
"}")
        self.lineEditSmtpAdres = QtWidgets.QLineEdit(AyarlarForm)
        self.lineEditSmtpAdres.setGeometry(QtCore.QRect(590, 60, 220, 35))
        self.lineEditSmtpAdres.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditSmtpAdres.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditSmtpAdres.setObjectName("lineEditSmtpAdres")
        self.lineEditOkulAdi = QtWidgets.QLineEdit(AyarlarForm)
        self.lineEditOkulAdi.setGeometry(QtCore.QRect(180, 10, 631, 41))
        self.lineEditOkulAdi.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditOkulAdi.setObjectName("lineEditOkulAdi")
        self.pushButton = QtWidgets.QPushButton(AyarlarForm)
        self.pushButton.setGeometry(QtCore.QRect(590, 280, 211, 61))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(AyarlarForm)
        self.label.setGeometry(QtCore.QRect(100, 20, 71, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AyarlarForm)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 67, 19))
        self.label_2.setObjectName("label_2")
        self.comboBoxGorevli = QtWidgets.QComboBox(AyarlarForm)
        self.comboBoxGorevli.setGeometry(QtCore.QRect(180, 60, 220, 35))
        self.comboBoxGorevli.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBoxGorevli.setEditable(False)
        self.comboBoxGorevli.setObjectName("comboBoxGorevli")
        self.timeEditMailSaat = QtWidgets.QTimeEdit(AyarlarForm)
        self.timeEditMailSaat.setGeometry(QtCore.QRect(180, 100, 220, 35))
        self.timeEditMailSaat.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.timeEditMailSaat.setObjectName("timeEditMailSaat")
        self.label_3 = QtWidgets.QLabel(AyarlarForm)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 151, 20))
        self.label_3.setObjectName("label_3")
        self.lineEditSmtpKulAdi = QtWidgets.QLineEdit(AyarlarForm)
        self.lineEditSmtpKulAdi.setGeometry(QtCore.QRect(590, 100, 220, 35))
        self.lineEditSmtpKulAdi.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditSmtpKulAdi.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditSmtpKulAdi.setObjectName("lineEditSmtpKulAdi")
        self.lineEditSmtpPortNo = QtWidgets.QLineEdit(AyarlarForm)
        self.lineEditSmtpPortNo.setGeometry(QtCore.QRect(590, 180, 220, 35))
        self.lineEditSmtpPortNo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditSmtpPortNo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditSmtpPortNo.setObjectName("lineEditSmtpPortNo")
        self.lineEditSmtpParola = QtWidgets.QLineEdit(AyarlarForm)
        self.lineEditSmtpParola.setGeometry(QtCore.QRect(590, 140, 220, 35))
        self.lineEditSmtpParola.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditSmtpParola.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditSmtpParola.setObjectName("lineEditSmtpParola")
        self.lineEditUsbId = QtWidgets.QLineEdit(AyarlarForm)
        self.lineEditUsbId.setGeometry(QtCore.QRect(180, 140, 220, 35))
        self.lineEditUsbId.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditUsbId.setMaxLength(1)
        self.lineEditUsbId.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditUsbId.setObjectName("lineEditUsbId")
        self.lineEditDemoVideo = QtWidgets.QLineEdit(AyarlarForm)
        self.lineEditDemoVideo.setGeometry(QtCore.QRect(180, 180, 220, 35))
        self.lineEditDemoVideo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditDemoVideo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditDemoVideo.setObjectName("lineEditDemoVideo")
        self.lineEditKisiLimiti = QtWidgets.QLineEdit(AyarlarForm)
        self.lineEditKisiLimiti.setGeometry(QtCore.QRect(180, 220, 220, 35))
        self.lineEditKisiLimiti.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditKisiLimiti.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditKisiLimiti.setObjectName("lineEditKisiLimiti")
        self.label_4 = QtWidgets.QLabel(AyarlarForm)
        self.label_4.setGeometry(QtCore.QRect(100, 220, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(AyarlarForm)
        self.label_5.setGeometry(QtCore.QRect(50, 180, 111, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AyarlarForm)
        self.label_6.setGeometry(QtCore.QRect(110, 140, 61, 31))
        self.label_6.setObjectName("label_6")
        self.checkBoxTLS = QtWidgets.QCheckBox(AyarlarForm)
        self.checkBoxTLS.setGeometry(QtCore.QRect(600, 230, 211, 25))
        self.checkBoxTLS.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBoxTLS.setAutoFillBackground(False)
        self.checkBoxTLS.setObjectName("checkBoxTLS")
        self.label_7 = QtWidgets.QLabel(AyarlarForm)
        self.label_7.setGeometry(QtCore.QRect(436, 70, 151, 20))
        self.label_7.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(AyarlarForm)
        self.label_8.setGeometry(QtCore.QRect(490, 140, 101, 31))
        self.label_8.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(AyarlarForm)
        self.label_9.setGeometry(QtCore.QRect(450, 110, 141, 20))
        self.label_9.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(AyarlarForm)
        self.label_10.setGeometry(QtCore.QRect(440, 220, 141, 31))
        self.label_10.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(AyarlarForm)
        self.label_11.setGeometry(QtCore.QRect(470, 180, 111, 31))
        self.label_11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_11.setObjectName("label_11")

        self.retranslateUi(AyarlarForm)
        QtCore.QMetaObject.connectSlotsByName(AyarlarForm)

    def retranslateUi(self, AyarlarForm):
        _translate = QtCore.QCoreApplication.translate
        AyarlarForm.setWindowTitle(_translate("AyarlarForm", "Ayarlar Ekranı"))
        self.lineEditSmtpAdres.setPlaceholderText(_translate("AyarlarForm", "SMTP Sunucu Adresi..."))
        self.lineEditOkulAdi.setPlaceholderText(_translate("AyarlarForm", "Okul Adı..."))
        self.pushButton.setText(_translate("AyarlarForm", "Ayarları Kaydet"))
        self.label.setText(_translate("AyarlarForm", "Okul Adı :"))
        self.label_2.setText(_translate("AyarlarForm", "Görevli :"))
        self.label_3.setText(_translate("AyarlarForm", "Mail Gönderim Saati :"))
        self.lineEditSmtpKulAdi.setPlaceholderText(_translate("AyarlarForm", "SMTP Kullanıcı Adı..."))
        self.lineEditSmtpPortNo.setPlaceholderText(_translate("AyarlarForm", "SMTP Port No..."))
        self.lineEditSmtpParola.setPlaceholderText(_translate("AyarlarForm", "SMTP Parola..."))
        self.lineEditUsbId.setPlaceholderText(_translate("AyarlarForm", "USB ID (0-1)..."))
        self.lineEditDemoVideo.setPlaceholderText(_translate("AyarlarForm", "Demo Video Adı..."))
        self.lineEditKisiLimiti.setPlaceholderText(_translate("AyarlarForm", "Kişi Sınırı..."))
        self.label_4.setText(_translate("AyarlarForm", "Kişi Sınırı :"))
        self.label_5.setText(_translate("AyarlarForm", "Demo Video Adı :"))
        self.label_6.setText(_translate("AyarlarForm", "USB ID :"))
        self.checkBoxTLS.setText(_translate("AyarlarForm", "SMTP TLS Durumu"))
        self.label_7.setText(_translate("AyarlarForm", "SMTP Sunucu Adresi:"))
        self.label_8.setText(_translate("AyarlarForm", "SMTP Parola :"))
        self.label_9.setText(_translate("AyarlarForm", "SMTP Kullanıcı Adı :"))
        self.label_10.setText(_translate("AyarlarForm", "SMTP TLS Aktif mi ?:"))
        self.label_11.setText(_translate("AyarlarForm", "SMTP Port No :"))
import views.sources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AyarlarForm = QtWidgets.QWidget()
    ui = Ui_AyarlarForm()
    ui.setupUi(AyarlarForm)
    AyarlarForm.show()
    sys.exit(app.exec_())
