# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kullanicilar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormKullanici(object):
    def setupUi(self, FormKullanici):
        FormKullanici.setObjectName("FormKullanici")
        FormKullanici.resize(821, 508)
        FormKullanici.setStyleSheet("* {\n"
"}\n"
"#FormKullanici{\n"
"    background-image: url(:/images/bg.png);\n"
"    background:#28595e;\n"
"}\n"
"QLineEdit, QComboBox, QTimeEdit, QTableView{\n"
"color:#333533;\n"
"background:rgba(85,170,255,100);\n"
"border-style:outset;\n"
"border: solid 1px;\n"
"border-radius:10px\n"
"}\n"
"QPushButton{\n"
"background-color:#4361ee;\n"
"border-style:outset;\n"
"border-radius:10px\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#ef233c;\n"
"border-style:inset;\n"
"border-radius:10px\n"
"}\n"
"QCheckBox{\n"
"background:rgba(85,170,255,0);\n"
"border-style:outset;\n"
"color:white;\n"
"}\n"
"QLabel{\n"
"background:rgba(85,170,255,0);\n"
"color:white;\n"
"}")
        self.groupBoxVeriler = QtWidgets.QGroupBox(FormKullanici)
        self.groupBoxVeriler.setGeometry(QtCore.QRect(20, 10, 581, 241))

        self.groupBoxVeriler.setObjectName("groupBoxVeriler")
        self.label_12 = QtWidgets.QLabel(self.groupBoxVeriler)
        self.label_12.setGeometry(QtCore.QRect(60, 100, 51, 21))

        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBoxVeriler)
        self.label_13.setGeometry(QtCore.QRect(10, 200, 111, 16))

        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBoxVeriler)
        self.label_14.setGeometry(QtCore.QRect(40, 150, 81, 16))

        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBoxVeriler)
        self.label_15.setGeometry(QtCore.QRect(30, 50, 91, 20))

        self.label_15.setObjectName("label_15")
        self.lineEditKullaniciAdi = QtWidgets.QLineEdit(self.groupBoxVeriler)
        self.lineEditKullaniciAdi.setGeometry(QtCore.QRect(130, 30, 251, 41))
        self.lineEditKullaniciAdi.setObjectName("lineEditKullaniciAdi")
        self.lineEditParola = QtWidgets.QLineEdit(self.groupBoxVeriler)
        self.lineEditParola.setGeometry(QtCore.QRect(130, 80, 251, 41))
        self.lineEditParola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditParola.setObjectName("lineEditParola")
        self.lineEditKullaniciAdiSoyadi = QtWidgets.QLineEdit(self.groupBoxVeriler)
        self.lineEditKullaniciAdiSoyadi.setGeometry(QtCore.QRect(130, 130, 251, 41))
        self.lineEditKullaniciAdiSoyadi.setObjectName("lineEditKullaniciAdiSoyadi")
        self.lineEditKullaniciMail = QtWidgets.QLineEdit(self.groupBoxVeriler)
        self.lineEditKullaniciMail.setGeometry(QtCore.QRect(130, 180, 401, 41))
        self.lineEditKullaniciMail.setObjectName("lineEditKullaniciMail")
        self.groupBox = QtWidgets.QGroupBox(FormKullanici)
        self.groupBox.setGeometry(QtCore.QRect(630, 30, 171, 221))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButtonKaydet = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonKaydet.setEnabled(False)
        self.pushButtonKaydet.setGeometry(QtCore.QRect(20, 180, 130, 30))

        self.pushButtonKaydet.setObjectName("pushButtonKaydet")
        self.pushButtonVazgec = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonVazgec.setEnabled(False)
        self.pushButtonVazgec.setGeometry(QtCore.QRect(20, 140, 130, 30))

        self.pushButtonVazgec.setObjectName("pushButtonVazgec")
        self.pushButtonSil = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonSil.setGeometry(QtCore.QRect(20, 60, 130, 30))

        self.pushButtonSil.setObjectName("pushButtonSil")
        self.pushButtonGuncelle = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonGuncelle.setGeometry(QtCore.QRect(20, 100, 130, 30))

        self.pushButtonGuncelle.setObjectName("pushButtonGuncelle")
        self.pushButtonYeniKayit = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonYeniKayit.setGeometry(QtCore.QRect(20, 20, 130, 30))

        self.pushButtonYeniKayit.setObjectName("pushButtonYeniKayit")
        self.tableView = QtWidgets.QTableView(FormKullanici)
        self.tableView.setGeometry(QtCore.QRect(20, 260, 781, 231))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(FormKullanici)
        QtCore.QMetaObject.connectSlotsByName(FormKullanici)

    def retranslateUi(self, FormKullanici):
        _translate = QtCore.QCoreApplication.translate
        FormKullanici.setWindowTitle(_translate("FormKullanici", "Kullanıcılar Ekranı"))
        self.groupBoxVeriler.setTitle(_translate("FormKullanici", "Kullanıcı Bilgileri"))
        self.label_12.setText(_translate("FormKullanici", "Parola:"))
        self.label_13.setText(_translate("FormKullanici", "E-posta Adresi:"))
        self.label_14.setText(_translate("FormKullanici", "Adı Soyadı:"))
        self.label_15.setText(_translate("FormKullanici", "Kullanıcı Adı:"))
        self.lineEditKullaniciAdi.setPlaceholderText(_translate("FormKullanici", "Kullanıcı Adı..."))
        self.lineEditParola.setPlaceholderText(_translate("FormKullanici", "Parola..."))
        self.lineEditKullaniciAdiSoyadi.setPlaceholderText(_translate("FormKullanici", "Personel Adı Soyadı..."))
        self.lineEditKullaniciMail.setPlaceholderText(_translate("FormKullanici", "Kullanıcı E-posta Adresi..."))
        self.pushButtonKaydet.setText(_translate("FormKullanici", "Kaydet"))
        self.pushButtonVazgec.setText(_translate("FormKullanici", "Vazgeç"))
        self.pushButtonSil.setText(_translate("FormKullanici", "Sil"))
        self.pushButtonGuncelle.setText(_translate("FormKullanici", "Değiştir"))
        self.pushButtonYeniKayit.setText(_translate("FormKullanici", "Yeni Kayıt"))
import views.sources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormKullanici = QtWidgets.QWidget()
    ui = Ui_FormKullanici()
    ui.setupUi(FormKullanici)
    FormKullanici.show()
    sys.exit(app.exec_())
