# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(437, 353)
        Form.setStyleSheet("* {\n"
"font-size:15px;\n"
"font-family:Century Gothic, sans-serif;\n"
"}\n"
"#Form{\n"
"    background-image: url(:/images/bg.png);\n"
"    background:#28595e\n"
"}\n"
"QFrame{\n"
"border:solid 10px rgb(0,0,0);\n"
"background-image:url(:images/bg.png);\n"
"}\n"
"QLineEdit{\n"
"    color: rgb(114, 159, 207);\n"
"background-color:#405361;\n"
"font-size:18px;\n"
"border-style:outset;\n"
"border-radius:10px\n"
"}\n"
"QPushButton{\n"
"background-color:#ced1d8;\n"
"border-style:outset;\n"
"border-radius:10px\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(224,0,0);\n"
"border-style:inset;\n"
"border-radius:10px\n"
"}\n"
"QCheckBox{\n"
"background:rgba(85,170,255,0);\n"
"border-style:outset;\n"
"color:white;\n"
"}\n"
"QLabel{\n"
"background:rgba(85,170,255,0);\n"
"color:red;\n"
"font-style:italic bold;\n"
"font-size:16px;\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 18, 191, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 240, 261, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEditKullaniciAdi = QtWidgets.QLineEdit(Form)
        self.lineEditKullaniciAdi.setGeometry(QtCore.QRect(80, 70, 261, 41))
        self.lineEditKullaniciAdi.setObjectName("lineEditKullaniciAdi")
        self.lineEditParola = QtWidgets.QLineEdit(Form)
        self.lineEditParola.setGeometry(QtCore.QRect(80, 130, 261, 41))
        self.lineEditParola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditParola.setObjectName("lineEditParola")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login Ekranı"))
        self.pushButton.setText(_translate("Form", "Giriş Yap"))
        self.lineEditKullaniciAdi.setPlaceholderText(_translate("Form", "Kullanıcı Adı..."))
        self.lineEditParola.setPlaceholderText(_translate("Form", "Parola..."))
import views.sources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_LoginForm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
